/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: tBUykdo9Wjz1oMcqFiag8z4o71aS9HNASveynyG3DrfRmV3cE70wlcpYVuIxXSj+LY46DaK9S3MYWTsbHqSO6Q==
 */

/* eslint-disable */
// tslint:disable

import Users from './users'

interface Posts {
  background: string
  content: Buffer
  exert: string
  /**
   * @default nextval('posts_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'posts_id'}
  is_published: boolean
  tweet_id: string
  /**
   * @default nextval('posts_user_id_seq'::regclass)
   */
  user_id: Users['id']
}
export default Posts;

interface Posts_InsertParameters {
  background: string
  content: Buffer
  exert: string
  /**
   * @default nextval('posts_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'posts_id'}
  is_published: boolean
  tweet_id: string
  /**
   * @default nextval('posts_user_id_seq'::regclass)
   */
  user_id?: Users['id']
}
export type {Posts_InsertParameters}
