/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: uTx5lZ4Quv9UnIG9Zvr0SZLCA3KTQiRNKuj6rSmcSbCSN1CbQ90rqXkI0AheSsUqFbu3ey16mxzZ+cqz2WwhlA==
 */

/* eslint-disable */
// tslint:disable

interface Users {
  avatar: string
  /**
   * @default nextval('users_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'users_id'}
  name: string
  twitter_id: string
}
export default Users;

interface Users_InsertParameters {
  avatar: string
  /**
   * @default nextval('users_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'users_id'}
  name: string
  twitter_id: string
}
export type {Users_InsertParameters}
